[package]
name = "number-guesser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
min_max_traits = "0.1.0"
num-traits = "0.2.15"
